# values.yaml
app:
  name: api-app

metadata:
  name: api-service

image:
  repository: kara21/my-app
  tag: v4

port: 8080

replicaCount: 1

postgres:
  name: postgres
  image:
    repository: postgres
    tag: "15"
  port: 5432
